#!/usr/bin/env python
import unittest
import sys, os
sys.path.append(os.getcwd())

loader = unittest.TestLoader()
suite = loader.discover('test', pattern='test*.py')
unittest.TextTestRunner(verbosity=2).run(suite)
